### ISSUE TITLE
merge statements failing on insert triggers for Anchor model tables

### ISSUE THREAD

**Issue by mzwarthoed** [Roenbaeck/anchor#127]
Some time ago I decided to upgrade our Anchor Model website using the latest build (0.99.4). 
We have been using an old version for more than 6 years and I ran into issues with support of using other schema's in SQL server; which is fixed in the new version. 
We are using merge statements a lot to insert / update data in the tables for the anhor model attributes. I noticed that the new version generates insert triggers on all of these attribute tables. 
The issue is that I cannot use those merge statements anymore, because the merge statements needs an update trigger next to the insert trigger when you try execute a merge statement which has both an update and an insert action (or no trigger at all). 
I've written a disable script for these specific triggers which I can run after implementation of each change, because the generated code will enable those triggers again with every change and I figured I don't need these triggers anyway.
I thought this issue was worth mentioning.

**Comment by delostilos** [comment]
You could comment out the line (with a # ):
- SQL/SQLServer/uni/CreateAttributeTriggers.js

in the file _SQLServer_uni.directive_. Then the Attribute Triggers are not generated.
Beware that it also effects the triggers on the views! So maybe it is better to also comment out:
- SQL/SQLServer/uni/CreateAnchorTriggers.js
- SQL/SQLServer/uni/CreateTieTriggers.js

**Comment by mzwarthoed** [comment]
Thanks for the reply. I will have a look to see if this presents a better solution than disabling those triggers after changing the Anchor Model in the database. I know those triggers on the views are very useful, so don't want to screw that up. But now i Know the option with the .js files gives me the flexibility to see what works best for our situation.

**Comment by Roenbaeck** [comment]
With https://github.com/Roenbaeck/anchor/commit/d7d6f4f910fbb77c1f47d1e95447150d7112d1d8 generation of triggers can now be switched off. This is available in the online test version.
