### ISSUE TITLE
Feature request: fix idempotency problem on Vertica projections

### ISSUE THREAD

**Issue by agoloborodko** [Roenbaeck/anchor#128]
When generating SQL code with following settings (as shown on screenshot), the app creates SQL code with "CREATE PROJECTION" statement (shown on second screenshot). 
When run generated script second time (i.e., after adding new objects), it fails with "projection XXX already exists" error, so the script is slightly unidempotent. However, Vertica allows to run "CREATE PROJECTION IF NOT EXISTS" statement, which fixes the problem.

![image](https://user-images.githubusercontent.com/44665786/81974892-e1d95480-962e-11ea-915d-834d6cc7497e.png)
![image](https://user-images.githubusercontent.com/44665786/81975262-6b892200-962f-11ea-98b4-546f3762a158.png)

**Comment by Roenbaeck** [comment]
Sorry for the delay, this is now fixed in: https://github.com/Roenbaeck/anchor/commit/86d51cae55f1a2c03255d3af4f20c11d9284b4f0 
It is available in the test version of the online modeler.
