### ISSUE TITLE
Historized Attribute or Historized Knotted Attribute

### ISSUE THREAD

**Issue by dboggs85** [Roenbaeck/anchor#13]
SQL code generator does not work.  Toggled to make both instances static and the generator works.

**Comment by jangorecki** [comment]
It could be nice to report some of your environment details, os, browser, versions. And did you checked it against some other browser, which.

**Comment by dboggs85** [comment]
Sorry Jan. Not a developer and I'm a newbie to Git on top of that. I'm a business guy trying to get my startup off the ground who thinks AM (specifically the modeler on code generator) are fantastic tools so please bear with me. Windows 7 OS and latest version (just updated today) of Chrome.  Happy to share other relevant details but you'll need to prompt me. Thanks for the guidance.

**Comment by dboggs85** [comment]
Test version of the modeler.

**Comment by Roenbaeck** [comment]
Is this issue still active? I have not been able to reproduce it.

**Comment by dboggs85** [comment]
Just reproduced it using the Actor model (the one that automatically pops up when I click on the Online Modeler (test version) link.  Changed Target database from Microsoft SQL Sever to PostgreSQL. Clicked on SQL code but no code generated.  Changed the 4 historized attributes to static attributes, clicked on SQL code and the code was generated.  Chrome Version 45.0.2454.101 m. PC info below.

![systeminfo](https://cloud.githubusercontent.com/assets/8496979/10280719/1d45359c-6b3d-11e5-8c83-2eeb12a2feb6.png)

**Comment by nicholas-peterson** [comment]
I believe the online tool does not currently generate PostgreSQL code. I think you're ascribing significance to the historized/static attributes when really the only thing that mattered was the target database.

**Comment by dboggs85** [comment]
So if you select PostgreSQL and click SQL code as shown in the first screen shot of the Actor AM below the resulting code as shown in the second screen shot is not PostgreSQL code?  Note I've toggled all the historized attributes in the Actor AM to static.  When they are left as historized and I click SQL code nothing happens, i.e., no code is generated as shown in the second screen shot below.  What am I missing here?
![image](https://cloud.githubusercontent.com/assets/8496979/12
![image](https://cloud.githubusercontent.com/assets/8496979/12342067/b319d238-baf4-11e5-808d-4de209652ce2.png)
342058/9fd6b222-baf4-11e5-8507-4f013340af4b.png)

**Comment by dboggs85** [comment]
[Doc1.docx](https://github.com/Roenbaeck/anchor/files/91199/Doc1.docx)

**Comment by dboggs85** [comment]
Sorry.  The images didn't come through on the first post.  See above doc for the screen shots.

**Comment by nicholas-peterson** [comment]
Hmm I stand corrected, I guess I so often use CRT and historized attributes I just assumed it never worked.

**Comment by dboggs85** [comment]
Merged with #92
