### ISSUE TITLE
Constraint  violation error for nonrestatable attribute

### ISSUE THREAD

**Issue by KvitkaAndrey** [Roenbaeck/anchor#141]
Hi,
I uncheck Restatable option for attribute PS_FIO_Person_FName, but
TRIGGER it_PS_FIO_Person_FName ON PS_FIO_Person_FName
INSTEAD OF INSERT insert restatable values, causing constraint (rfPS_FIO_Person_FName(PS_FIO_PS_ID,PS_FIO_Person_FName,PS_FIO_ChangedAt)=0) violation error.

Is this the right behavior?
Can it be better to make sure that the consecutive identical values for nonrestatable attribute are ignored without breaking the constraint?

**Comment by Roenbaeck** [comment]
The "Restatable" option only controls whether a CHECK constraint preventing restatements should be added. If you also want the trigger to silently ignore restatements you also need to select the "Idempotent" option, which controls the behavior of the trigger.

**Comment by KvitkaAndrey** [comment]
Thanks, 
I didn't understand the idempotency option correctly.
