### ISSUE TITLE
MS SQL version compatibility

### ISSUE THREAD

**Issue by KvitkaAndrey** [Roenbaeck/anchor#142]
Hi,
Which versions of MS SQL the generated code is compatible with?

**Comment by Roenbaeck** [comment]
Earlier than SQL Server 2005 - No go.
SQL Server 2005 - Worked once upon a time, but not tested in a long time.
SQL Server 2008 - Worked just a few years ago, but also not tested in a long time.
SQL Server 2012 or later - No problems whatsoever.
