### ISSUE TITLE
PostgreSQL code generation

### ISSUE THREAD

**Issue by rpalston** [Roenbaeck/anchor#16]
I'm using the test modeler (http://roenbaeck.github.io/anchor/) which includes the ability to select PostgreSQL as a destination DB. The SQL code generator does not appear to work, it works fine if I use MS SQL Server as the destination DB.

**Comment by jangorecki** [comment]
@rpalston you should provide some more information, what commands are failing etc. You may need to adjust output SQL script for fixes mentioned in #10. If you found any new issues and fixes for them you can also add them to #10 to have all postgres sql script fixes in one place.

**Comment by rpalston** [comment]
Sorry for not being clear but the SQL Code menu item under 'generate' does nothing at all when the PostgreSQL is set as the target database in the test online modeler. Using the example model when I select the SQL Code menu item if the target database is MS SQL Server an SQL code window (populated with T-SQL for an MSSQL server)  appears. Using the same example model but with a target of PostgreSQL the SQL Code menu item does nothing. I am using the test modeler here: http://roenbaeck.github.io/anchor/

**Comment by jangorecki** [comment]
I will not help on that as it seems to be javascript issue. Anyway you should check it in another browser and report browsers and their versions, and your OS may be useful too.

**Comment by rpalston** [comment]
That helped. Chrome v44 on Windows 7 is creating a JavaScript error when I try to generate SQL code for PostgreSQL. Changed to FF v38.05 and it generates PostgreSQL SQL fine. Thanks for pointing me in the right direction.
