### ISSUE TITLE
Feature - have a save dialog when saving to local file.

### ISSUE THREAD

**Issue by delostilos** [Roenbaeck/anchor#226]
We use git to stare our models. It would be nice if we have a save dialog where we can select the location and the name of the model. Then we can point it to our git repo. Where we also store the version of the modeler used to create the model.
We use this version of the modeler local in FireFox.

**Comment by delostilos** [comment]
Even if you use the "File System Access API" it is still a user setting in the browser. You can set the option to ask where the file has to be stored on your filesystem. This solves the problem. So I'm closing this issue.

**Comment by Roenbaeck** [comment]
Where do you change this setting in the browser? I think it would be nice to make people aware of this either on the forum or as a blog post on anchormodeling.com.

**Comment by delostilos** [comment]
It is the setting where you want to put your downloaded files. There you can set  it to ask every time you download a file where to place it.
