### ISSUE TITLE
[Question] How to handle the derived attribute of an anchor?

### ISSUE THREAD

**Issue by simkimsia** [Roenbaeck/anchor#231]
let's say we have an anchor or tie called LineItem

it has the following attributes: 
1. LineItemQuantity
2. LineItemPrice

So to calculate the Subtotal of the LineItem: i need to 

LineItemQuantity * LineItemPrice

So how do I define the LineItemSubtotal?

is it also an attribute of the anchor / tie called LineItem?

Does it make sense to have foreign keys of the two attributes LineItemQuantity, LineItemPrice be inside the LineItemSubtotal?

**Comment by Roenbaeck** [comment]
Let's say you have LineItemQuantity (LIQ) and LineItemPrice (LIP) and you want to store the result of a calculation LIQ * LIP as an additional attribute LineItemSubtotal (LIS). Then both LIQ and LIP will reference the same anchor identity LI_ID in LI_LineItem. The result of the calculation should also reference the very same LI_ID from LIS. The identity in the anchor is what identifies something as being the same thing, so no additional foreign keys are necessary.

For example:

LI_ID LIQ_LineItemQuantity
42    11

LI_ID LIP_LineItemPrice
42    $9

LI_ID LIS_LineItemSubtotal
42    $99

**Comment by simkimsia** [comment]
Suppose that i also want to store the function logic as a string (i know this is very trivial example but bear with me)

Calculation (this is historized) LISC
`round(self.quantity.value * self.price.value, 2)` => this is the string value, so the id is LISC_ID


LI_ID LIQ_LineItemQuantity
42 11

LI_ID LIP_LineItemPrice
42 $9

LI_ID LIS_LineItemSubtotal LIQ_ID LIP_ID LISC_ID
42 $99 42 42 37


can.i do this?

**Comment by simkimsia** [comment]
Sorry for the multiple messages.

I have realized I misunderstood anchor modeling. Based on this, https://www.anchormodeling.com/wp-content/uploads/2010/08/AM_Cheat_Sheet.pdf i wll redo the naming to be closer to anchor modeling.

I also didn't realize that attribute tables should just use the anchor id as primary key.

By the way, i think your teachable course is not available to be signed up. I keep getting a school is not open for enrollment.

### LI_LineItem (anchor)
(p) LI_ID => 42
_metadata 

### LIQTY_LineItemQuantity (attribute)
(p) LI_ID => 42
LIQTY_Quantity => 11
_metadata 

### LIPRC_LineItemPrice (attribute)
(p) LI_ID => 42
LIPRC_Price => $9
_metadata 

### LISTL_LineItemSubtotal (attribute)
(p) LI_ID => 42
LISTL_Subtotal => $99
_metadata 


Now that I have this, I like to keep track of the calculation logic that generated the Subtotal.

I'm more interested in using anchor modeling to build a OLTP based web app that's easy to make changes to. So, less for data warehousing needs. I'm using postgres, so I am not using SQL server.

### CT_ContentType 

THis is a table that stores info about the other tables in the database. This is a common pattern in frameworks like Django

(p) CT_ID Name
1  LI_LineItem
2  LIQTY_LineItemQuantity
3  LIPRC_LineItemPrice
4 LISTL_LineItemSubtotal

### CTCAL_AttributeCalculation (attribute)
(p) CT_ID => 4
(p) CTCAL_From => 2023-01-01
CTCAL_Output => `round(self.quantity.value * self.price.value, 2)`
_metadata 

Then I got stuck here. Because I initially wanted to link the CTCAL_AttributeCalculation with LISTL_LineItemSubtotal. But when I re-read about `ties` it seems that they only tie anchors and not attributes.

So I decided to create a tie between CT_ContentType with LI_LineItem instead.

I assume there can be multiple ties between two anchors to represent different relationships.

LICT_LineItem_ContentType_Calculation
(p) LI_ID => 42
(p) CT_ID => 4
(p) LICT_From => 2023-01-01
LICT_Calculation => `round(LIQTY_LineItemQuantity * LIPRC_LineItemPrice, 2)`


Am I doing this correctly?
