### ISSUE TITLE
Possible Issue With Evolution Table-valued Function

### ISSUE THREAD

**Issue by rfrasier-mlp** [Roenbaeck/anchor#28]
The issue with the `dbo._Evolution` table-valued function is that it does not handle the fact that the attribute tables are accounted for with the syntax `dbo.<attribute-view-syntax-goes-here>_Annex` or `dbo.<attribute-view-syntax-goes-here>_Posit` while the attribute views have the syntax of **`<two-letter-anchor-mnemonic>_<three-letter-attribute_mnemonic>_<anchor-descriptor>_<attribute-descriptor>`** such as `dbo.CO_NAM_Company_Name` as an example view name.  Specifically, the `dbo._Evolution` function returns `NULL` for `version` and `Past` for the tables while it returns `Missing` for `Existence` for the views as well as the correct `version` number.  I looked at the SQL code and it's clear that `sys.views` is never called to retrieve any information on the views.  This is a very important function for production issues related to Anchor Modeling and I would hope this can be fixed or advised upon quickly.  Many thanks ahead of time for any comments and help on this issue.  Kind regards.

**Comment by Roenbaeck** [comment]
This is now fixed in the test version.
