### ISSUE TITLE
Minor syntax issue in CreateAttributeAssembledViews.js

### ISSUE THREAD

**Issue by rfrasier-mlp** [Roenbaeck/anchor#38]
In the test version, I believe there is simply a missing comma in the file SQL/SQLServer/crt/CreateAttributeAssembledViews.js which is giving an "Incorrect syntax near..." error when executed after using the SQL code generation.

On line 49 of CreateAttributeAssembledViews.js, the ":" (colon) should be replaced with a "," (comma) to separate the assertion  and identity column names in the generated SQL code.

Many thanks and please advise.

**Comment by Roenbaeck** [comment]
Thanks for noticing this. I added the missing comma sign and generation now works again.
