### ISSUE TITLE
_Evolution Table-valued Function returns NULL for tables with Future Existence

### ISSUE THREAD

**Issue by rfrasier-mlp** [Roenbaeck/anchor#51]
When using the _Evolution table-valued function, it does correctly return the tables with the correct value for `Existence`; however, in my case with just two versions, when I use a previous date in the _Evolution script it rewinds correctly but in the returned table only `NULL` values are returned for all of the "Future" tables.  Is this the intended functionality or should I be seeing a value for the Future tables?  Many thanks ahead of time!

**Comment by Roenbaeck** [comment]
I took a look at this and it was just laziness that had prevented the version from displaying for other than "Present" tables. The test version now has an improved _Evolution function.
