### ISSUE TITLE
[FeatureRequest] Modules for Sisulator and DataTypeConverter

### ISSUE THREAD

**Issue by computerlyrik** [Roenbaeck/anchor#58]
These two are perfectly separatable from the rest of the code.
Makes changes, fixes much more easy.

If this approach is supported by project owner @Roenbaeck  and Community, i will generate a pull request to do so.

**Comment by Roenbaeck** [comment]
If split the Sisulator code should preferably sync with the Sisulator.js found in https://github.com/Roenbaeck/sisula/blob/ETL/Sisulator.js

**Comment by computerlyrik** [comment]
Okay, but i do not know these JScript engine.

Around line 176 you use
``` 
var reader = new ActiveXObject("Scripting.FileSystemObject");
```

Any ideas how to merge the Browser-JS Sisulator code with the JScript one? Is there any decision engine you know about?

After that, it should be possible to work with git submodules to make the source available to your sisula and anchor projects.

**Comment by computerlyrik** [comment]
Perhaps we can use a callback to tell the Sisulator how to get the directives?

**Comment by Roenbaeck** [comment]
Possibly, or we could just maintain the two separately anyway. If splitting out things, we should probably also do so for the layout engine. It's pretty self contained.

**Comment by computerlyrik** [comment]
I found a elegant way to do this for Sisulator:

https://github.com/Roenbaeck/anchor/compare/master...computerlyrik:feature_module
- Sisulator.js and Map.js separate files
- tried to sync the Web-Code to your (newer?) JScript code from sisula-Project
- extracted the directives-code and wrote a elegant callback method - should also work for sisula Projekt!
- Minimum Changes on index.html

For the git-submodule part - on Top of the working Code above, i extracted the two JS-Files in a extra Repo:
https://github.com/computerlyrik/anchor/compare/feature_module...computerlyrik:feature_git_submodule

To setup the submodule(s) run  ```git submodule update --init```.

Tell me, when your review and feedback is done - i'd like to go for a Pull Request ;)

**Comment by computerlyrik** [comment]
We may discuss the names ```directives``` [Sisulator.js] and ```getDirectives``` [index.html].
It's the Sisulator just does not know anything about **Directive** - it just processes files follwing convention.

**Comment by delostilos** [comment]
These Modules are created:

- DataTypeConverter
- Defaults
- Inheritance
- LayoutEngine
- Sisulator
