### ISSUE TITLE
Description of roles in XML is overwritten by Anchor description

### ISSUE THREAD

**Issue by delostilos** [Roenbaeck/anchor#62]
Hi,

When I save the model to XML the description of the role is overwritten by the description of the attached anchor. I think it is nicer to overwrite only if there is no description present for a role.

Regards,
JJ.

**Comment by delostilos** [comment]
Hi,

On my local installation of the 0.98 modeler I changed the the toXML function of the Tie at line 3573 from:
`this.addDescriptionXML(roleElement, schema,  component.description);`
to:
`this.addDescriptionXML(roleElement, schema,  role.description || component.description);`
Now the discription is taken from the role and if it is empty it picks up the component (Anchor) description.

Regards,
JJ.

**Comment by Roenbaeck** [comment]
Thanks JJ, 

I will try to remember to add this the next time I touch the code :) 

Or, I could add you to the project if you'd like? 

Best, 

Lars 

On 12.04.2016 09:41, Juan Jose van der Linden wrote: 

> Hi, 
> 
> On my local installation of the 0.98 modeler I changed the the toXML function of the Tie at line 3573 from:
> this.addDescriptionXML(roleElement, schema, component.description);
> to:
> this.addDescriptionXML(roleElement, schema, role.description || component.description);
> Now the discription is taken from the role and if it is empty it picks up the component (Anchor) description. 
> 
> Regards,
> JJ. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub [1] 
> 
> !DSPAM:570cd3e2204471403478991!
 

Links:
------
[1] https://github.com/Roenbaeck/anchor/issues/62#issuecomment-208758992

**Comment by delostilos** [comment]
Hi Lars,

You can add me to the project. Then I can make the change myself :-)

Regards,
JJ.
