### ISSUE TITLE
don't create MD5 function in SQL Server 2016

### ISSUE THREAD

**Issue by lBilali** [Roenbaeck/anchor#88]
From documentation https://msdn.microsoft.com/en-us/library/ms174415.aspx
`For SQL Server 2014 and earlier, allowed input values are limited to 8000 bytes.`
Meaning SQL Server 2016 has removed the limit of 8000 bytes for input.
This makes it unnecessary to create a UDF.

**Comment by Roenbaeck** [comment]
Thanks, this has now been implemented by https://github.com/Roenbaeck/anchor/commit/4c45bdcd955badfc57b4a75d230a7259b19d865c.
