### ISSUE TITLE
Broken PNG screenshot and SVG export

### ISSUE THREAD

**Issue by thiemo-taken** [Roenbaeck/anchor#94]
I am using latest stable on Firefox 53.0.3 (32bit, Windows 7 64 bit)
- Taking a PNG screenshot makes only a [grayish image](http://anchor-modeling.1047469.n5.nabble.com/file/n5706732/Model.png)
- Exporting SVG generates a [file ](http://anchor-modeling.1047469.n5.nabble.com/file/n5706732/Model.svg) which viewed in the very same Firefox results in error message 

> Ungeschlossenes Token
Adresse: file:///C:/Users/kellnert/Downloads/Model.svg
Zeile Nr. 1, Spalte 205:

Translation to englisch would approximately be

> Open token
address: file:///C:/Users/kellnert/Downloads/Model.svg
Line n° 1, column 205:

However, the SVG screenshot works.

**Comment by Roenbaeck** [comment]
I think this is fixed in the test version now.

**Comment by Roenbaeck** [comment]
It seems PNG generation is disabled in the browsers for the time being, so I have removed the option from the menu.
